# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: changelog

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  run-changelog-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download unclog binary
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: OffchainLabs/unclog
          name: unclog
          run-id: 12679708867

      - name: Get new changelog files
        id: new-changelog-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            changelog/**.md

      - name: Run lint command
        env:
          ALL_ADDED_MARKDOWN: ${{ steps.new-changelog-files.outputs.added_files }}
        run: chmod +x unclog && ./unclog check -fragment-env=ALL_ADDED_MARKDOWN
